name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  ci:
    runs-on: ubuntu-latest
    container: madninja/builder-erlang:1

    steps:
    - uses: actions/checkout@v2

    - name: Dialyzer
      run: rebar3 dialyzer

    - name: Run tests
      run: rebar3 do eunit, ct
